repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.2.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
        files: ^backend/.*\.(py)$
      # Run the formatter.
      - id: ruff-format
        files: ^backend/.*\.(py)$



  # Add ESLint for frontend directory files.
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.21.0 # Use the desired eslint version.
    hooks:
      - id: eslint
        name: eslint (frontend)
        entry: bash -c 'cd frontend && npm run lint $(git diff --cached --name-only --diff-filter=ACM | grep -E "\.(js|ts|jsx|tsx)$" | grep "^frontend/" | sed "s|^frontend/||")'
        language: system
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [ file ]
        additional_dependencies: [ ]
        args: [ "frontend" ]
