FROM python:3.13.9-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app
RUN mkdir /app/indexer_gifts

# Copy requirements and install dependencies
COPY backend/indexer_gifts/requirements.txt ./indexer_gifts/requirements.txt

RUN pip install --upgrade pip && \
    pip install -r indexer_gifts/requirements.txt

COPY backend/core ./core
RUN pip install -e ./core

# Copy the source code
COPY backend/indexer_gifts ./indexer_gifts
