FROM python:3.11.6-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app
RUN mkdir /app/indexer_price

# Copy requirements and install dependencies
COPY backend/indexer_price/requirements.txt ./indexer_price/requirements.txt

RUN pip install --upgrade pip && \
    pip install -r indexer_price/requirements.txt

COPY backend/core ./core
RUN pip install -e ./core

# Copy the source code
COPY backend/indexer_price ./indexer_price
