FROM python:3.11.6-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app
RUN mkdir /app/indexer_gifts

# Copy requirements and install dependencies
COPY backend/core/requirements.txt ./core/requirements.txt
COPY backend/core/requirements-test.txt ./core/requirements-test.txt

RUN pip install --upgrade pip && \
    pip install -r core/requirements.txt && \
    pip install -r core/requirements-test.txt

RUN pip install -e ./core
