FROM python:3.11.6-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app
RUN mkdir /app/api

# Copy requirements and install dependencies
COPY backend/api/requirements.txt ./api/requirements.txt

RUN pip install --upgrade pip && \
    pip install -r api/requirements.txt

COPY backend/core ./core
RUN pip install -e ./core

# Copy the source code
COPY backend/api ./api
