FROM python:3.11.6-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app
RUN mkdir /app/community_manager

# Copy requirements and install dependencies
COPY backend/community_manager/requirements.txt ./community_manager/requirements.txt

RUN pip install --upgrade pip && \
    pip install -r community_manager/requirements.txt

COPY backend/core ./core
RUN pip install -e ./core

# Copy the source code
COPY backend/community_manager ./community_manager
