FROM python:3.11.6-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app
RUN mkdir /app/indexer_blockchain

COPY backend/alembic.ini .

# Copy requirements and install dependencies
COPY backend/indexer_blockchain/requirements.txt ./indexer_blockchain/requirements.txt

RUN pip install --upgrade pip && \
    pip install -r indexer_blockchain/requirements.txt

COPY backend/core ./core
RUN pip install -e ./core

# Copy the source code
COPY backend/indexer_blockchain ./indexer_blockchain
