FROM golang:1.23.3-alpine AS builder

LABEL stage=gobuilder

ENV CGO_ENABLED=0
ENV GOOS=linux

RUN apk update --no-cache && apk add --no-cache tzdata

WORKDIR /build

COPY backend/transaction-lookup/go.mod .
COPY backend/transaction-lookup/go.sum .

RUN go mod download

COPY backend/transaction-lookup/. .

RUN go build -ldflags="-s -w" -o /worker ./cmd/worker/...

FROM alpine

RUN apk update --no-cache && apk add --no-cache ca-certificates

COPY --from=builder /worker /worker

CMD ["/worker"]
