"""jetton decimals

Revision ID: 1b167f412dfd
Revises: 3abd43626972
Create Date: 2025-11-17 18:18:22.039696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b167f412dfd"
down_revision: Union[str, None] = "3abd43626972"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jetton",
        sa.Column("decimals", sa.Integer(), nullable=False, server_default="9"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jetton", "decimals")
    # ### end Alembic commands ###
