name: Lint and test the code on the branch

on:
  push:
    branches-ignore:
      - main


jobs:
  test-python:
    uses: ./.github/workflows/test-python.yml

  lint-python:
    uses: ./.github/workflows/lint-python.yml

  lint-typescript:
    uses: ./.github/workflows/lint-typescript.yml
