name: Build and Push Frontend

on:
  workflow_call:  # Makes it reusable
    inputs:        # Optional: Use inputs to customize behavior
      branch:
        required: false
        type: string
        description: The branch to deploy from.
      environment:
        required: true
        type: string
        description: Environment to deploy

jobs:
  build-and-push-frontend:
    permissions:
      contents: read  # Required for checkout
      packages: write  # Required for pushing to GHCR
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Git Commit SHA
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lowercase repository name
        run: |
          echo "REPO=${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: config/docker/frontend.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}/gateway-tool-frontend:latest
            ghcr.io/${{ env.REPO }}/gateway-tool-frontend:${{ env.GIT_SHA }}
