name: Deploy Application

on:
  push:
    branches:
      - feat/package

jobs:
  build-and-push-frontend:
    uses: ./.github/workflows/build-and-push-frontend.yml
    with:  # Pass inputs if defined in the reusable workflow
      branch: feat/package

  deploy:
    needs: build-and-push-frontend
    uses: ./.github/workflows/deployment.yml
    secrets:
      VPS_IP: ${{ secrets.VPS_IP }}
      VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
      VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
