name: Lint and test Typescript code

on:
  workflow_call:

env:
  PROJECT_DIR: ./frontend

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

        with:
          node-version: 23.11
          cache: yarn
          cache-dependency-path: frontend/yarn.lock

      - name: Install dependencies
        working-directory: ${{ env.PROJECT_DIR }}
        run: yarn install --frozen-lockfile

      - name: Run eslint
        working-directory: ${{ env.PROJECT_DIR }}
        run: yarn run lint --max-warnings 0
        continue-on-error: true  # Temporary enabled to not block other MRs
